### ISSUE TITLE
Add a README file for this project

### ISSUE THREAD

**Issue by AyushTripathiIITP** [AyushTripathiIITP/WebBlog.com#1]
https://drive.google.com/file/d/1XRMFvvfmqeTt9HS9IExU-yEA2IULeQ_2/view?usp=sharing

Download this video and add it in readme.md file also add all basic tools that are being used in this project
Add all necessary details that you might think good.
Make it as appealing as possible

**Comment by AyushTripathiIITP** [comment]
Make sure you make a push request to branch different from main

**Comment by AyushTripathiIITP** [comment]
Go ahead

**Comment by Yash-Ainapure** [comment]
Heyy @AyushTripathiIITP  Could you please check this pr and merge it?
