### ISSUE TITLE
Remove node_module folder from the project

### ISSUE THREAD

**Issue by AyushTripathiIITP** [AyushTripathiIITP/WebBlog.com#2]
Add a .gitignore file and when making a push request remove the node_modules folder
It might save space

**Comment by AyushTripathiIITP** [comment]
Make sure you make a push request to branch different from main

**Comment by dipaksinha1** [comment]
Hi @AyushTripathiIITP , Can you please assign this issue to me?

**Comment by AyushTripathiIITP** [comment]
sure go ahead

**Comment by dipaksinha1** [comment]
Hi @AyushTripathiIITP , Can you please review the pull request?
