### ISSUE TITLE
Fixing multiple post retrival error

### ISSUE THREAD

**Issue by AyushTripathiIITP** [AyushTripathiIITP/WebBlog.com#3]
https://github.com/AyushTripathiIITP/WebBlog.com/assets/101452500/1d6d5fc6-f734-46fc-bc6d-55382ff53bde

have a detailed decription of the problem in above video

**Comment by AyushTripathiIITP** [comment]
Make sure you make a push request to branch different from main

**Comment by dipaksinha1** [comment]
Hi @AyushTripathiIITP , Can you please assign this issue to me?

**Comment by dipaksinha1** [comment]
Hi @AyushTripathiIITP , Can you please review and merge the changes? .Please let me know if any issues.
