### ISSUE TITLE
Update pacakge.json to add nodemon

### ISSUE THREAD

**Issue by dipaksinha1** [AyushTripathiIITP/WebBlog.com#8]
Need to add nodemon package to automatically restart the node application when file changes in the directory are detected.

This will save time and effort in restarting the server for any changes in node app. as it will detect changes automatically.

Documentation Link
https://www.npmjs.com/package/nodemon

**Comment by AyushTripathiIITP** [comment]
go ahead i am assigning it to you @dipaksinha1

**Comment by SharmaDhruv2511** [comment]
can i work on this issue @dipaksinha1 if @AyushTripathiIITP has not any problem ?

**Comment by dipaksinha1** [comment]
Hi @AyushTripathiIITP , I have raised a PR for this issue. Please review and let me know if any changes are needed.

PR #12
