### ISSUE TITLE
Code Refactoring and File Restructuring

### ISSUE THREAD

**Issue by dipaksinha1** [AyushTripathiIITP/WebBlog.com#9]
This issue is raised to propose and discuss a series of code refactoring and file restructuring changes in the Node.js application. The goal is to enhance code maintainability, readability, and overall project structure.

**Comment by AyushTripathiIITP** [comment]
sure go ahead @dipaksinha1

**Comment by dipaksinha1** [comment]
PR #13

**Comment by dipaksinha1** [comment]
Hi @AyushTripathiIITP, please review and merge the pull request.

**Comment by dipaksinha1** [comment]
Closing this issue as this pr is merged.
